version: '3.3'
services:
  lunchbot:
    container_name: lunchbot-app
    image: "ghcr.io/bentomsett/lunchbot:latest"
    restart: always
    depends_on:
      - mongo
    environment:
      - SLACK_CLIENT_SECRET=$SLACK_CLIENT_SECRET
      - SLACK_CLIENT_ID=$SLACK_CLIENT_ID
      - SLACK_APP_TOKEN=$SLACK_APP_TOKEN
      - SLACK_APP_URL=$SLACK_APP_URL
  mongo:
    container_name: lunchbot-db
    image: mongo
    volumes:
      - mongodb:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  mongodb:

networks:
  default:
    external:
      name: nginx

