version: '3.3'
services:
  lunchbot:
    restart: always
    build: .
    ports:
      - "3001:3001"
    environment:
      - SLACK_CLIENT_SECRET=$SLACK_CLIENT_SECRET
      - SLACK_CLIENT_ID=$SLACK_CLIENT_ID
      - SLACK_APP_TOKEN=$SLACK_APP_TOKEN
      - SLACK_APP_URL=$SLACK_APP_URL
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    command: mongod --quiet --logpath /dev/null
volumes:
  mongodb:
